## Numpy array and basics 
learn about numpy with chai or code


In [1]:
import numpy as np

## creating array from list

In [ ]:
arr_1d = np.array([1, 2, 3, 4])
print("1D array: ", arr_1d)

arr_2d = np.array([[1, 2, 3], [4, 5, 6]])
print("2D array: ", arr_2d)

1D array:  [1 2 3 4]
2D array:  [[1 2 3]
 [4 5 6]]


## List vs numpy array

In [ ]:
py_list = [1, 2, 3]
print("Python list multiplication ", py_list * 2)

np_array = np.array([1, 2, 3])  # element wise mulitplication
print("Python array multiplication ", np_array * 2)

import time

start = time.time()
py_list = [i * 2 for i in range(10000)]
print("\n List operation time: ", time.time() - start)


start = time.time()
np_array = np.arange(10000) * 2
print("\n Numpy operation time: ", time.time() - start)

Python list multiplication  [1, 2, 3, 1, 2, 3]
Python array multiplication  [2 4 6]

 List operation time:  0.0020551681518554688

 Numpy operation time:  0.00021648406982421875


## creating array from scratch


In [ ]:
zeros = np.zeros((3, 4))  # creating zeros array
print("zeros array: \n", zeros)

ones = np.ones((2, 3))  # creating ones array
print("one array: \n", ones)

full = np.full((2, 2), 7)  # creating full array
print("full array: \n", full)

random = np.random.random((2, 3))
print("full array: \n", random)

sequence = np.arange(0, 11, 2)
print("sequence array: \n", sequence)

zeros array: 
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
one array: 
 [[1. 1. 1.]
 [1. 1. 1.]]
full array: 
 [[7 7]
 [7 7]]
full array: 
 [[0.23600515 0.66966232 0.74671364]
 [0.68962337 0.01939254 0.82705887]]
sequence array: 
 [ 0  2  4  6  8 10]


## Vector, Matrix and Tensor

In [24]:
vector = np.array([1, 2, 3])
print("Vector: \n", vector)

matrix = np.array([[1, 2, 3], [4, 5, 6]])
print("Matrix: \n", matrix)

tensor = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print("Tensor: \n", tensor)

Vector: 
 [1 2 3]
Matrix: 
 [[1 2 3]
 [4 5 6]]
Tensor: 
 [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


## Array properties

In [29]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
print("Shape: ", arr.shape)
print("Dimension: ", arr.ndim)
print("Size: ", arr.size)
print("Dtype: ", arr.dtype)

Shape:  (2, 3)
Dimension:  2
Size:  6
Dtype:  int64


## Array Reshsaping

In [33]:
arr = np.arange(12)
print("Original array: ", arr)

reshaped = arr.reshape((3, 4))
print("Reshaped array: ", reshaped)

Original array:  [ 0  1  2  3  4  5  6  7  8  9 10 11]
Reshaped array:  [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
